# SPDX-License-Identifier: LGPL-2.1-or-later
# Opt-in dependency selection. Invoke selection before the first find_package(Qt6),
# then verify targets after Qt/PySide/Shiboken discovery. Runtime origins require the
# verifier's separate --load-python command in the selected environment.

function(freecad_select_qualified_qt)
    if(NOT FREECAD_QUALIFIED_QT_PREFIX)
        return()
    endif()
    if(FREECAD_LIBPACK_USE)
        message(FATAL_ERROR "Qualified Conda Qt selection cannot be combined with a LibPack")
    endif()
    if(TARGET Qt6::Core)
        message(FATAL_ERROR "Select qualified Qt before finding any Qt package")
    endif()
    if(NOT FREECAD_QUALIFIED_QT_PLATFORM)
        message(FATAL_ERROR "Set FREECAD_QUALIFIED_QT_PLATFORM to the selected Conda platform")
    endif()
    file(REAL_PATH "${FREECAD_QUALIFIED_QT_PREFIX}" _prefix)
    if(NOT FREECAD_QUALIFIED_QT_CATALOG)
        set(FREECAD_QUALIFIED_QT_CATALOG
            "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../package/qt-pdf/distribution.json"
            CACHE FILEPATH "Reviewed Qt delivery catalogue")
    endif()
    if(NOT FREECAD_QUALIFIED_QT_PYTHON)
        if(WIN32)
            set(_python "${_prefix}/python.exe")
        else()
            set(_python "${_prefix}/bin/python")
        endif()
        set(FREECAD_QUALIFIED_QT_PYTHON "${_python}"
            CACHE FILEPATH "Python interpreter from the selected Conda environment")
    endif()
    file(REAL_PATH "${FREECAD_QUALIFIED_QT_PYTHON}" _python)
    cmake_path(IS_PREFIX _prefix "${_python}" NORMALIZE _python_selected)
    if(NOT _python_selected OR NOT EXISTS "${_python}")
        message(FATAL_ERROR "Qualified Qt requires Python from the selected Conda environment")
    endif()
    set(_verifier "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../package/qt-pdf/verify_delivered_qt.py")
    execute_process(
        COMMAND "${FREECAD_QUALIFIED_QT_PYTHON}" -B "${_verifier}"
            --prefix "${_prefix}" --catalog "${FREECAD_QUALIFIED_QT_CATALOG}"
            --platform "${FREECAD_QUALIFIED_QT_PLATFORM}"
        RESULT_VARIABLE _status OUTPUT_VARIABLE _proof ERROR_VARIABLE _error
    )
    if(NOT _status EQUAL 0)
        message(FATAL_ERROR "Qualified Qt selection failed: ${_proof}${_error}")
    endif()
    file(WRITE "${CMAKE_BINARY_DIR}/qualified-qt-selection.json" "${_proof}")
    string(JSON _count LENGTH "${_proof}" cmake_dirs)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
        string(JSON _name MEMBER "${_proof}" cmake_dirs ${_index})
        string(JSON _directory GET "${_proof}" cmake_dirs "${_name}")
        set("${_name}_DIR" "${_directory}" CACHE PATH "Reviewed Qt package location" FORCE)
        set("${_name}_DIR" "${_directory}" PARENT_SCOPE)
    endforeach()
    set(Python_EXECUTABLE "${FREECAD_QUALIFIED_QT_PYTHON}" CACHE FILEPATH "Selected Python" FORCE)
    set(Python3_EXECUTABLE "${FREECAD_QUALIFIED_QT_PYTHON}" CACHE FILEPATH "Selected Python" FORCE)
    set(Python_ROOT_DIR "${_prefix}" CACHE PATH "Selected Python prefix" FORCE)
    set(Python3_ROOT_DIR "${_prefix}" CACHE PATH "Selected Python prefix" FORCE)
    set(Python_EXECUTABLE "${FREECAD_QUALIFIED_QT_PYTHON}" PARENT_SCOPE)
    set(Python3_EXECUTABLE "${FREECAD_QUALIFIED_QT_PYTHON}" PARENT_SCOPE)
    set(Python_ROOT_DIR "${_prefix}" PARENT_SCOPE)
    set(Python3_ROOT_DIR "${_prefix}" PARENT_SCOPE)
    set(_prefixes "${_prefix}")
    if(WIN32)
        list(APPEND _prefixes "${_prefix}/Library")
    endif()
    list(APPEND _prefixes ${CMAKE_PREFIX_PATH})
    set(CMAKE_PREFIX_PATH "${_prefixes}" PARENT_SCOPE)
    set(FREECAD_QUALIFIED_QT_SELECTED_PREFIX "${_prefix}" PARENT_SCOPE)
    message(STATUS "Selected reviewed Conda Qt; runtime library verification remains separate")
endfunction()

function(freecad_verify_qualified_qt_targets)
    if(NOT FREECAD_QUALIFIED_QT_PREFIX)
        return()
    endif()
    if(NOT FREECAD_QUALIFIED_QT_SELECTED_PREFIX)
        message(FATAL_ERROR "Qualified Qt target verification requires prior selection")
    endif()
    get_property(_targets DIRECTORY PROPERTY IMPORTED_TARGETS)
    set(_arguments)
    foreach(_target IN LISTS _targets)
        if(NOT _target MATCHES "^Qt6::[A-Za-z0-9_]+$" AND
           NOT _target MATCHES "^(PySide6::pyside6(qml)?|Shiboken6::libshiboken)$")
            continue()
        endif()
        get_target_property(_type "${_target}" TYPE)
        if(NOT _type STREQUAL "SHARED_LIBRARY")
            continue()
        endif()
        get_target_property(_configurations "${_target}" IMPORTED_CONFIGURATIONS)
        set(_suffixes "_GENERIC")
        foreach(_configuration IN LISTS _configurations)
            if(_configuration AND NOT _configuration MATCHES "-NOTFOUND$")
                string(TOUPPER "${_configuration}" _configuration)
                list(APPEND _suffixes "_${_configuration}")
            endif()
        endforeach()
        foreach(_suffix IN LISTS _suffixes)
            if(_suffix STREQUAL "_GENERIC")
                set(_suffix "")
            endif()
            get_target_property(_location "${_target}" "IMPORTED_LOCATION${_suffix}")
            if(_location AND NOT _location MATCHES "-NOTFOUND$")
                list(APPEND _arguments --target "${_target}" "${_location}")
            endif()
            get_target_property(_implib "${_target}" "IMPORTED_IMPLIB${_suffix}")
            if(_implib AND NOT _implib MATCHES "-NOTFOUND$")
                list(APPEND _arguments --import-library "${_target}" "${_implib}")
            endif()
        endforeach()
    endforeach()
    set(_verifier "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../package/qt-pdf/verify_delivered_qt.py")
    execute_process(
        COMMAND "${FREECAD_QUALIFIED_QT_PYTHON}" -B "${_verifier}"
            --prefix "${FREECAD_QUALIFIED_QT_SELECTED_PREFIX}"
            --catalog "${FREECAD_QUALIFIED_QT_CATALOG}"
            --platform "${FREECAD_QUALIFIED_QT_PLATFORM}" ${_arguments}
        RESULT_VARIABLE _status OUTPUT_VARIABLE _proof ERROR_VARIABLE _error
    )
    if(NOT _status EQUAL 0)
        message(FATAL_ERROR "Qualified Qt imported targets differ: ${_proof}${_error}")
    endif()
    string(JSON _targets ERROR_VARIABLE _missing GET "${_proof}" imported_targets)
    if(_missing)
        message(FATAL_ERROR "Qualified Qt proof omitted imported target origins")
    endif()
    file(WRITE "${CMAKE_BINARY_DIR}/qualified-qt-targets.json" "${_proof}")
endfunction()
